### ISSUE TITLE
能介绍下@Property 的DataType.LIST DataType.OBJ的用法吗？

### ISSUE THREAD

**Issue by shadow-shadow** [yezhihao/jt808-server#3]
在解码类似以下不定长协议时
|  header  | body_length  |  list<obj>|crc
obj=(msgType, msgobj ) 

@Property(index = 9, type = DataType.LIST, desc =“”)
DataType.OBJ的 对象类型需要根据 msgType来确定，而且对象字节长度不一样
DataType.OBJ 的length 如何设置？

**Comment by yezhihao** [comment]
固定的length 直接写数值





动态的length 也可以指定属性名


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shadow-shadow"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 上午10:25
收件人:&nbsp;"yezhihao/jt808-server"<jt808-server@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yezhihao/jt808-server] 能介绍下@Property 的DataType.LIST DataType.OBJ的用法吗？ (#3)





 
在解码类似以下不定长协议时
 |  header  | body_length  |  list|crc
 obj=(msgType, msgobj )
 
@Property(index = 9, type = DataType.LIST, desc =“”)
 DataType.OBJ的 对象类型需要根据 msgType来确定，而且对象字节长度不一样
 DataType.OBJ 的length 如何设置？

**Comment by shadow-shadow** [comment]
谢谢，您的代码很优雅！
最近在弄32960、17691的协议解析。
解码器只能选LengthFieldBasedFrameDecoder

指定属性名也不太方便，这两个协议存在 
| header | body_length | list<obj （obj里面还嵌套list<obj>）>| bcc
所以最上层的list 的length 用属性名定义也有不能实现的地方。

有点嵌套的感觉在里面，还是没太领会框架的奥秘。
